# Generated by Django 5.1.7 on 2025-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('favourite_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
